<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework></PropertyGroup><ItemGroup><Compile Include="../../ProjectEden/src/Patches/MegaAssembler/MegaExchangerLogisticsPatches.cs" Link="Patch.cs" /><Compile Include="../../ProjectEden/src/Patches/MegaAssembler/ParallelExchangerIndex.cs" Link="ParallelExchangerIndex.cs" /></ItemGroup></Project>