<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net472</TargetFramework><LangVersion>latest</LangVersion></PropertyGroup><ItemGroup><Compile Include="../../ProjectEden/src/Patches/MegaAssembler/BeltSlotSelection.cs" Link="BeltSlotSelection.cs" /><Compile Include="../../ProjectEden/src/Patches/MegaAssembler/SlotDataStore.cs" Link="SlotDataStore.cs" /></ItemGroup></Project>
