<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net472</TargetFramework><LangVersion>latest</LangVersion></PropertyGroup><ItemGroup><Compile Include="../../ProjectEden/src/Patches/MegaAssembler/MegaInputTransfer.cs" Link="MegaInputTransfer.cs"/><Compile Include="../../ProjectEden/src/Patches/MegaAssembler/MegaStationPatches.cs" Link="MegaStationPatches.cs" /></ItemGroup></Project>
